config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: :create
  resources :projects
  
  resources :tickets do
    resources :comments, except: [:index, :new, :show, :destroy]
  end
  
  resources :tags, except: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :creator, class_name: "User"
  belongs_to :ticket

  validates :body, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tickets, dependent: :destroy

  validates :name, presence: true

  def open_tickets
    self.tickets.where.not(status: 'fixed')
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  def self.STATUSES
    ['new', 'blocked', 'in_progress', 'fixed']
  end

  has_many :taggings
  has_many :tickets, through: :taggings

  validates :name, presence: true

  def self.get_tags_tickets
    result = {}
    Tag.all.each do |tag|
      result[tag.name] = tag.tickets.size
    end
    result
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :project
  belongs_to :creator, class_name: 'User'
  belongs_to :assignee, class_name: 'User', optional: true
  
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :comments, dependent: :destroy

  validates :name, presence: true
  validates :project_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  has_many :tickets 

  validates :name, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "Must be logged in to do that."
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user, only: [:create, :edit]
  before_action :set_ticket, only: [:create, :edit, :update]
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def create
    @comment = @ticket.comments.build(comment_params)
    @comment.creator = current_user

    if @comment.save
      if params[:ticket_status].present?
        @ticket.update_attribute(:status, params[:ticket_status])
      end

      flash[:success] = "Your comment was added."
      redirect_to ticket_path(@ticket)
    else
      render 'tickets/show'
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      flash[:notice] = "Your comment was updated."
      redirect_to ticket_path(@ticket)
    else

    end
  end

  def destroy

  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_ticket
    @ticket = Ticket.find(params[:ticket_id])
  end

  def set_comment
    @comment = @ticket.comments.find(params[:id])
  end

  def require_same_user
    if current_user != @comment.creator
      flash[:notice] = "You can only edit your own comments"
      redirect_to ticket_path(@ticket)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, except: [:index, :new, :create]
  before_action :require_user, except: [:show, :index]

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "A new project was created."
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:notice] = "The project was updated"
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "You have deleted the #{@project.name} project."
    redirect_to root_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description)
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
    user = User.where(name: params[:name]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, you've logged in."
      redirect_to root_path
    else
      flash[:error] = "There is something wrong with your username or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:edit, :update, :destroy]
  before_action :require_user, except: :index

  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      flash[:notice] = "A new tag was created."
      redirect_to tags_path
    else
      render :new
    end

  end

  def edit

  end

  def update
    if @tag.update(tag_params)
      flash[:notice] = "The tag was updated."
      redirect_to tags_path
    else
      render :edit
    end
  end

  def destroy
    @tag.destroy
    flash[:notice] = "You have deleted the #{@tag.name} tag."
    redirect_to tags_path
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]

  def index 
    if params[:project].present?
      @tickets = Project.find(params[:project]).tickets
    else
      @tickets = Ticket.all
    end

    if params[:status].present?
      @tickets = @tickets.where(status: params[:status])
    end

    if params[:tag].present?
      @tickets = @tickets.joins(:tags).where("tags.id": params[:tag])
    end
  end

  def show
    @comment = Comment.new
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params.merge(creator: current_user))

    if @ticket.save
      flash[:notice] = "A new ticket was created."
      redirect_to ticket_path(@ticket)
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket was updated."
      redirect_to ticket_path(@ticket)
    else
      render :edit
    end 
  end

  def destroy
    @ticket.destroy
    flash[:notice] = "You have deleted the #{@ticket.name} ticket."
    redirect_back fallback_location: root_path
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:name, :body, :status, :project_id, :assignee_id, tag_ids: [])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
    
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully registered."
      redirect_to root_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tag_list(ticket)
    if ticket.tags.any?
      ticket.tags.map(&:name).join(', ')
    else
      "-"
    end
  end

  def alphabetize(tags)
    tags.sort_by {|tag| tag.name.downcase}
  end
end

app/views/comments/_comment_form.html.erb
<%= render 'shared/errors', obj: @comment %>

<%= form_for [@ticket, @comment] do |f| %>
    <div class='control-group'>
      <%= f.label :body, 'Add a comment' %>
      <%= f.text_area :body, rows: 3, class: 'span4' %>
    </div>
    <p>Change status:</p>
    <%= select_tag :ticket_status, options_for_select(Tag.STATUSES, params[:status]), :include_blank => "Do not change" %>
    
    <div>
      <%= f.submit @comment.new_record? ? "Add Comment" : "Edit Comment", class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/comments/edit.html.erb
<%= render 'shared/content_title', title: "Edit comment" %>

<%= render 'comment_form' %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <h1>TICKETING</h1>
  <li>
    <%= link_to "Projects", root_path %>
  </li>
  <li>
    <%= link_to "Tickets", tickets_path %>
  </li>
  <li>
    <%= link_to "Tags", tags_path %>
  </li>
</ul>

<% if logged_in? %>
  <div class='pull-right'>
    <span>Logged in as: <%= current_user.name %></span>
    <%= link_to 'Log out', logout_path, class: 'btn btn-small' %>
  </div>
<% else %>
  <div class='pull-right'>
    <%= link_to 'Log in', login_path, class: 'btn btn-small' %>
  </div>
  <br>
  <br>
  <div class='pull-right'>
    <%= link_to 'Register', '/register', class: 'btn btn-small' %>
  </div>
<% end %>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ticketing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/projects/_form.html.erb
<div class="well">
  <%= form_for @project do |f| %>
    <div class="control-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="control-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %>
    </div>

    <%= f.submit(@project.new_record? ? "Create Project" : "Update Project", class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/projects/edit.html.erb
<%= render 'shared/content_title', title: "Edit Project" %>
<%= render 'shared/errors', obj: @project %>

<%= render 'form' %>

<%= link_to 'Back', project_path(@project) %>

app/views/projects/index.html.erb
<%= render 'shared/content_title', title: "Projects" %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Open Tickets</th>
      <th>Total Tickets</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td>
          <h2><%= link_to project.name, project_path(project) %></h2>
          <p><%= project.description %></p>  
        </td>
        <td><%= project.open_tickets.size %></td>
        <td><%= project.tickets.size %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to "New Project", new_project_path, class: 'btn btn-success' %>
</div>

app/views/projects/new.html.erb
<%= render 'shared/content_title', title: "New Project" %>
<%= render 'shared/errors', obj: @project %>
<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<%= render 'shared/content_title', title: @project.name %>

<h5><%= @project.description %></h5>


<%= link_to "Edit", edit_project_path(@project), class: 'btn' %>
<%= link_to "Delete", project_path(@project), method: 'delete', class: 'btn' %>


<h3>Tickets:</h3>

<%= render 'tickets/tickets_list', tickets: @project.tickets %>

app/views/shared/_content_title.html.erb
<p class='lead'>
  <h2><%= title %></h2>
  <hr>
</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class='row'>
    <div class='alert alert-error span8'>
      <h5>Please fix the following errors:</h5>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  </div>
<% end %>

app/views/tags/_form.html.erb
<div class="well">
  <%= form_for @tag do |f| %>
    <div class="control-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <%= f.submit(@tag.new_record? ? "Create Tag" : "Update Tag", class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/tags/_tags_list.html.erb
<% tags_tickets = Tag.get_tags_tickets %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tickets</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% alphabetize(@tags).each do |tag| %>
      <tr>
        <td>
          <h2><%= tag.name %></h2> 
        </td>
        <td><%= link_to tags_tickets[tag.name], '/tickets?tag=' + tag.id.to_s %></td>
        <td>
          <%= link_to "Edit", edit_tag_path(tag) %>
          <%= link_to "Delete", tag_path(tag), method: 'delete' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tags/edit.html.erb
<%= render 'shared/content_title', title: "Edit Tag" %>

<%= render 'shared/errors', obj: @tag %>

<%= render 'form' %>

<%= link_to "Back", tags_path %>

app/views/tags/index.html.erb
<%= render 'shared/content_title', title: "Tags" %>

<%= render 'tags_list' %>

<div>
  <%= link_to "New Tag", new_tag_path, class: 'btn btn-success' %>
</div>

app/views/tags/new.html.erb
<%= render 'shared/content_title', title: 'New Tag' %>

<%= render 'shared/errors', obj: @tag %>

<%= render 'form' %>

app/views/tickets/_filters.html.erb
<%= form_tag tickets_path, method: 'get', enforce_utf8: false do %>
  <div class="control-group">
    Show tickets from
    <%= select_tag :project, options_from_collection_for_select(Project.all, :id, :name, params[:project]), include_blank: "All Projects" %> 
    
    with status
    <%= select_tag :status, options_for_select(Tag.STATUSES, params[:status]), :include_blank => "Any Status" %>
    
    tagged
    <%= select_tag :tag, options_from_collection_for_select(alphabetize(Tag.all), :id, :name, params[:tag]), include_blank: "-" %>
  </div>
  <%= submit_tag 'Filter Tickets', class: 'btn' %>
  <%= link_to 'Clear', tickets_path, class: 'btn btn-primary' %>
<% end %>

app/views/tickets/_form.html.erb
<div class="well">
  <%= form_for @ticket do |f| %>
    <div class="control-group">
      <%= f.label :project %>
      <%= f.collection_select :project_id, Project.all, :id, :name, id: :ticket_project_id %>
    </div>
    
    <div class="control-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    
    <div class="control-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 5 %>
    </div>

    <div class="control-group">
      <%= f.label :status %>
      <%= f.select :status, Tag.STATUSES %>
    </div>

    <div class="control-group">
      <%= f.label :assignee, 'Assigned To' %>
      <%= f.collection_select :assignee_id, User.all, :id, :name, id: :ticket_assignee_id, include_blank: "No one" %>
    </div>

    <div class="control-group">
      <%= f.label 'Tags' %>
      <%= f.collection_select :tag_ids, Tag.all, :id, :name, {}, multiple: true, id: :ticket_tag_ids, size: Tag.count %>
    </div>
    
    <%= f.submit(@ticket.new_record? ? 'Create Ticket' : 'Update Ticket', class: 'btn btn-success') %>
  <% end %>
</div>

app/views/tickets/_tickets_list.html.erb
<% if tickets.empty? %>
  <p><em>There are no tickets matching the selected filters.</em></p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Assignee</th>
        <th>Status</th>
        <th>Tags</th>
        <th></th>
      </tr>
    </thead>
  
    <tbody>
      <% tickets.each do |ticket| %>
        <tr>
          <td><h2><%= link_to ticket.name, ticket_path(ticket) %></h2></td>
          <td><%= ticket.assignee ? ticket.assignee.name : '-' %></td>
          <td><%= ticket.status %></td>
          <td>
            <%= tag_list(ticket) %>
          </td>
          <td>
            <%= link_to "Edit", edit_ticket_path(ticket) %>
            <%= link_to "Delete", ticket_path(ticket), method: 'delete' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/tickets/edit.html.erb
<%= render '/shared/content_title', title: 'Edit Ticket' %>

<%= render 'shared/errors', obj: @ticket %>

<%= render 'form' %>

<%= link_to 'Back', url_for(:back) %>

app/views/tickets/index.html.erb
<%= render 'shared/content_title', title: "Tickets" %>

<%= render 'filters' %>

<%= render 'tickets_list', tickets: @tickets %>

<div>
  <%= link_to "New Ticket", new_ticket_path, class: 'btn btn-success' %>
</div>

app/views/tickets/new.html.erb
<%= render 'shared/content_title', title: 'New Ticket' %>

<%= render 'shared/errors', obj: @ticket %>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<%= render 'shared/content_title', title: @ticket.name %>

<p><strong>Description:</strong> <%= @ticket.body %></p>
<p><strong>Tags:</strong> <%= tag_list(@ticket) %></p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %>
<hr>
<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Creator</th>
      <th>Assignee</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @ticket.status %></td>
      <td><%= @ticket.creator.name %></td>
      <td><%= @ticket.assignee ? @ticket.assignee.name : '-' %></td>
    </tr>
  </tbody>
</table>

<h3>Comments:</h3>

<% @ticket.comments.each do |comment| %>
  <div class='well'>
    <p><%= comment.body %></p>
    <p>posted by <%= comment.creator.name %></p>
    <%= link_to 'Edit', edit_ticket_comment_path(@ticket, comment) %>
  </div>
<% end %>

<%= render 'comments/comment_form' %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: "Register" %>

<%= render '/shared/errors', obj: @user %>

<div class='well'>
  <%= form_for @user do |f| %>
    <div class='control-group'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class='control-group'>
      <%= f.label :email %>
      <%= f.text_field :email, type: 'email' %>
    </div>
    <div class='control-group'>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class='control-group'>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <%= f.submit "Register", class: 'btn btn-success' %>
  <% end %>
</div>